classes.dir=target/classes
component.inlineBindingPrefix=$
component.inlineBindingSuffix=
component.wellFormedTemplateRequired=false
customInfoPListContent=
principalClass=wong.Application
project.name=wong-hybrid
project.name.lowercase=wong-hybrid
project.type=application
webXML=false
webXML_CustomContent=
project.base=wo
